// 导出所有的action
export default {
  THEME_CHANGE: "THEME_CHANGE", //主题切换
  THEME_INIT: "THEME_INIT",   //初始化主题
  SHOW_THEME_VIEW: "SHOW_THEME_VIEW" , //显示主题
  POPULAR_REFRESH: "POPULAR_REFRESH",    //刷新加载
  POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",  //刷新失败
  POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS", //刷新成功
  POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS", // 上啦加载成功
  POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",      //上啦加载失败

}